version: '3'

networks:
  jenkinsdocker_default:
    external: true

services:
  nginx:
    image: nginx:1.12
    volumes:
      - ./etc/nginx/:/etc/nginx/
      - ./certs/jenkins:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - jenkinsdocker_default
