version: '3'

volumes:
  jenkins_home:

services:

  jenkins:
    build: ./build/ansible
    restart: unless-stopped
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      #JENKINS_ARGS: "--webroot=/var/cache/jenkins/war --httpPort=$HTTP_PORT --ajp13Port=$AJP_PORT --prefix=/jenkins"
    expose:
      - 50000
      - 8080
    volumes:
      - jenkins_home:/var/jenkins_home
