version: '3'

volumes:
  jenkins_home:

services:

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 50000
    volumes:
      - jenkins_home:/var/jenkins_home
